name: Composer outdated

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]

    name: Composer outdated - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: Composer outdated
        if: matrix.php == '8.1'
        run: composer outdated -D --strict --ignore phpunit/phpunit --ignore nikic/php-parser --ignore phpstan/phpstan

      - name: Composer outdated
        if: matrix.php == '8.2' || matrix.php == '8.3'
        run: composer outdated -D --strict --ignore phpunit/phpunit --ignore tomaj/nette-api --ignore nikic/php-parser --ignore phpstan/phpstan

      - name: Composer outdated
        if: matrix.php != '8.1' && matrix.php != '8.2' && matrix.php != '8.3'
        run: composer outdated -D --strict --ignore nikic/php-parser --ignore phpstan/phpstan
