name: PHP extensions finder

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  extensions_finder:
    runs-on: ubuntu-latest
    name: PHP extensions finder

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: Install PHP extensions finder as dev dependency
        run: composer require efabrica/php-extensions-finder --dev

      - name: PHP extensions finder
        if: matrix.php <= '8.1'
        run: composer update --no-progress --no-interaction

      - name: PHP extensions finder
        if: matrix.php >= '8.2'
        run: composer update --no-progress --no-interaction --ignore=ext-random
