name: PHP static analysis

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]

    name: PHPStan - PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      - name: Composer update
        if: matrix.php <= '8.1'
        run: composer update --no-progress --no-interaction --ignore-platform-req=ext-random

      - name: Composer update
        if: matrix.php >= '8.2'
        run: composer update --no-progress --no-interaction

      - name: PHPStan analyse
        run: vendor/bin/phpstan analyze src --level=max --no-progress
